import type { RunConfig } from "../types";

export const configFields: Array<{ key: keyof RunConfig; label: string; hint?: string; kind?: "bool" }> = [
  { key: "board", label: "Board" },
  { key: "num_snakes", label: "Snakes" },
  { key: "count", label: "count", hint: "parallel live games" },
  { key: "gpu_batch_games", label: "gpu_batch_games", hint: "games per search shard" },
  { key: "samples_per_gen", label: "Samples" },
  { key: "sims", label: "Sims" },
  { key: "c_puct", label: "C PUCT" },
  { key: "exploration_prob", label: "Explore" },
  { key: "draw_value", label: "Draw value" },
  { key: "max_turns", label: "Max turns" },
  { key: "skip_short_draw_turns", label: "Skip draws" },
  { key: "bootstrap_value", label: "Bootstrap", kind: "bool" },
  { key: "trunk_channels", label: "Channels" },
  { key: "trunk_blocks", label: "Blocks" },
  { key: "gpool_every", label: "GPool every" },
  { key: "train_steps", label: "Train steps" },
  { key: "batch_size", label: "Batch" },
  { key: "lr", label: "LR" },
  { key: "recency", label: "Recency" },
  { key: "buffer_size", label: "Buffer" },
  { key: "value_weight", label: "Value weight" },
  { key: "search_threads", label: "Threads" },
  { key: "eval_every", label: "Eval every" },
  { key: "eval_games", label: "Eval games" },
];
